Add MSRV 1.80 and test in CI (#302)
* Add MSRV 1.80

* Test 1.80.1 in CI

* Only test build on MSRV

* Fix deprecated GitHub actions output mechanism

* Make shellcheck happy

---------

Co-authored-by: Tim Süberkrüb <dev@timsueberkrueb.io>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -18,6 +18,29 @@ env:
   CARGO_TERM_COLOR: always
 
 jobs:
+  build-msrv:
+    name: Build with Minimum Supported Rust Version (MSRV)
+    runs-on: ubuntu-latest
+    outputs:
+      msrv: ${{ steps.extract_rust_version.outputs.msrv }}
+    steps:
+      - uses: actions/checkout@v4
+      - name: Extract Rust Version
+        id: extract_rust_version
+        run: |
+          rust_version=$(awk -F '"' '/rust-version/ {print $2; exit}' Cargo.toml)
+          if [ -z "$rust_version" ]; then
+            echo "Error: rust-version not found in Cargo.toml"
+            exit 1
+          fi
+          echo "msrv=$rust_version" >> "$GITHUB_OUTPUT"
+      - name: Set Up Rust Toolchain
+        uses: dtolnay/rust-toolchain@stable
+        with:
+          toolchain: ${{ steps.extract_rust_version.outputs.msrv }}
+      - uses: Swatinem/rust-cache@v2
+      - run: cargo build --all
+
   check:
     name: Check
     runs-on: ubuntu-latest
